apiVersion: v1
kind: Service
metadata:
  name: frontend--service
spec:
  type: ClusterIP
  selector:
    component: frontend
  ports:
    - port: 8501
      targetPort: 8501


apiVersion: apps/v1
kind: Deployment
metadata:
  name: frontend-deployment
spec:
  replicas: 2
  selector:
    matchLabels:
      component: frontend
  template:
    metadata:
      labels:
        component: frontend
    spec:
      containers:
        - name: frontend
          image: winterman10/test_nyc_frontend
          ports:
            - containerPort: 8501
