apiVersion: v1
kind: Service
metadata:
  name: api-cluster-ip-service
spec:
  type: ClusterIP
  selector: 
    component: api
  ports: 
    - port: 5000
      targetPort: 5000


apiVersion: apps/v1
kind: Deployment
metadata:
  name: flask-deployment
spec:
  replicas: 2
  selector:
    matchLabels:
      component: backend
  template:
    metadata:
      labels:
        component: backend
    spec:
      containers:
        - name: flask-backend
          image: winterman10/backend
          ports:
          - containerPort: 5000
